/**
 * Simple HTML Report Generator
 * 
 * A lightweight and reliable HTML report generator that focuses
 * on the most important assessment data without any complex processing
 * that might cause the app to crash.
 */

/**
 * Creates a simple but functional HTML report from assessment data
 */
export const generateSimpleHtmlReport = (assessmentData: any, setupData: any): string => {
  try {
    // Generate the HTML document with simple structure
    const html = `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Fire Risk Assessment - ${setupData?.substationName || 'Site'}</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 0; padding: 20px; }
          .container { max-width: 1000px; margin: 0 auto; }
          h1, h2, h3 { color: #1976d2; }
          table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
          th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
          th { background-color: #f2f2f2; }
          .section { margin-bottom: 30px; border-bottom: 1px solid #eee; padding-bottom: 20px; }
          .header { text-align: center; margin-bottom: 30px; }
          .image-gallery { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 15px; }
          .image { width: 150px; height: 150px; object-fit: cover; border: 1px solid #ddd; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>Fire Risk Assessment Report</h1>
            <h2>${setupData?.substationName || 'Site'}</h2>
            <p>Assessment Date: ${setupData?.assessmentDate ? new Date(setupData.assessmentDate).toLocaleDateString() : new Date().toLocaleDateString()}</p>
          </div>
          
          <!-- Assessment Setup -->
          <div class="section">
            <h2>1. Assessment Setup</h2>
            <table>
              <tr><th>Field</th><th>Value</th></tr>
              ${setupData ? Object.entries(setupData)
                .filter(([_, value]) => typeof value !== 'object')
                .map(([key, value]) => {
                  const formattedKey = key.replace(/([A-Z])/g, ' $1').replace(/^./, str => str.toUpperCase());
                  return `<tr><td>${formattedKey}</td><td>${value || 'Not specified'}</td></tr>`;
                }).join('') : '<tr><td colspan="2">No setup data available</td></tr>'}
            </table>
          </div>
          
          <!-- Assessment Results Summary -->
          <div class="section">
            <h2>2. Assessment Results</h2>
            <p>The following sections were assessed:</p>
            <ul>
              ${assessmentData?.passiveFireProtection ? '<li>Passive Fire Protection</li>' : ''}
              ${assessmentData?.activeFireProtection ? '<li>Active Fire Protection</li>' : ''}
              ${assessmentData?.transformers ? '<li>Transformer Risk</li>' : ''}
              ${assessmentData?.circuitBreakers ? '<li>Circuit Breaker Risk</li>' : ''}
              ${assessmentData?.cables ? '<li>Cable Risk</li>' : ''}
              ${assessmentData?.earthingAndLightning ? '<li>Earthing and Lightning</li>' : ''}
              ${assessmentData?.arcProtection ? '<li>Arc Protection</li>' : ''}
            </ul>
            <p>Please refer to the full assessment data for detailed information on each section.</p>
          </div>
          
          <!-- Footer -->
          <div style="text-align: center; margin-top: 40px;">
            <p>Generated by EFI Fire Risk Assessment App</p>
            <p>${new Date().toLocaleString()}</p>
          </div>
        </div>
      </body>
      </html>
    `;
    
    return html;
  } catch (error) {
    console.error('Error generating simple HTML report:', error);
    return `
      <!DOCTYPE html>
      <html>
        <head><title>Error in Report</title></head>
        <body>
          <h1>Error Generating Report</h1>
          <p>There was an error generating your report.</p>
        </body>
      </html>
    `;
  }
};
